package fsexchange.ws.stub.businesscollect;


import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BusinessCollectWebService service = new BusinessCollectWebService();
 * BusinessCollectWebServicePortType portType = service.getBusinessCollectWebServiceHttpPort();
 * portType.saveOrUpdateBusinessCollect(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BusinessCollectWebService", targetNamespace = "http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com", wsdlLocation = "http://19.129.80.36:8084/service/BusinessCollectWebService?wsdl")
public class BusinessCollectWebService extends Service {

	//http://19.129.80.36:8084/service
	//BusinessCollectWebService
	public static QName _getServiceName(){
		return new QName(
				"http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com",
		"BusinessCollectWebService");
	}
	
	public BusinessCollectWebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	

	/**
	 * 
	 * @return returns BusinessCollectWebServicePortType
	 */
	@WebEndpoint(name = "BusinessCollectWebServiceHttpPort")
	public BusinessCollectWebServicePortType getBusinessCollectWebServiceHttpPort() {
		return super
				.getPort(
						new QName(
								"http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com",
								"BusinessCollectWebServiceHttpPort"),
						BusinessCollectWebServicePortType.class);
	}

}
