package fsexchange.ws.stub.premservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * IPremWebService service = new IPremWebService();
 * IPremWebServicePortType portType = service.getIPremWebServiceHttpPort();
 * portType.getSpsxInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "IPremWebService", targetNamespace = "http://webhallWebService.webService.tjsoft.com", wsdlLocation = "http://19.129.80.36:8082/service/IPremWebService?wsdl")
public class IPremWebService extends Service {

	private final static URL IPREMWEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(fsexchange.ws.stub.premservice.IPremWebService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = fsexchange.ws.stub.premservice.IPremWebService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://19.129.80.36:8082/service/IPremWebService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://19.129.80.36:8082/service/IPremWebService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		IPREMWEBSERVICE_WSDL_LOCATION = url;
	}

	public IPremWebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IPremWebService() {
		super(IPREMWEBSERVICE_WSDL_LOCATION, new QName(
				"http://webhallWebService.webService.tjsoft.com",
				"IPremWebService"));
	}

	/**
	 * 
	 * @return returns IPremWebServicePortType
	 */
	@WebEndpoint(name = "IPremWebServiceHttpPort")
	public IPremWebServicePortType getIPremWebServiceHttpPort() {
		return super.getPort(new QName(
				"http://webhallWebService.webService.tjsoft.com",
				"IPremWebServiceHttpPort"), IPremWebServicePortType.class);
	}

}
