package fsexchange.ws.stub.premservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IPremWebServicePortType", targetNamespace = "http://webhallWebService.webService.tjsoft.com")
public interface IPremWebServicePortType {

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in4
	 * @param in3
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webhallWebService.webService.tjsoft.com")
	@RequestWrapper(localName = "getSpsxInfo", targetNamespace = "http://webhallWebService.webService.tjsoft.com", className = "fsexchange.webservice.premservice.GetSpsxInfo")
	@ResponseWrapper(localName = "getSpsxInfoResponse", targetNamespace = "http://webhallWebService.webService.tjsoft.com", className = "fsexchange.webservice.premservice.GetSpsxInfoResponse")
	public String getSpsxInfo(
			@WebParam(name = "in0", targetNamespace = "http://webhallWebService.webService.tjsoft.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://webhallWebService.webService.tjsoft.com") String in1,
			@WebParam(name = "in2", targetNamespace = "http://webhallWebService.webService.tjsoft.com") String in2,
			@WebParam(name = "in3", targetNamespace = "http://webhallWebService.webService.tjsoft.com") String in3,
			@WebParam(name = "in4", targetNamespace = "http://webhallWebService.webService.tjsoft.com") String in4);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webhallWebService.webService.tjsoft.com")
	@RequestWrapper(localName = "getDeptInfo", targetNamespace = "http://webhallWebService.webService.tjsoft.com", className = "fsexchange.webservice.premservice.GetDeptInfo")
	@ResponseWrapper(localName = "getDeptInfoResponse", targetNamespace = "http://webhallWebService.webService.tjsoft.com", className = "fsexchange.webservice.premservice.GetDeptInfoResponse")
	public String getDeptInfo(
			@WebParam(name = "in0", targetNamespace = "http://webhallWebService.webService.tjsoft.com") String in0);

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webhallWebService.webService.tjsoft.com")
	@RequestWrapper(localName = "getPermItemInfo", targetNamespace = "http://webhallWebService.webService.tjsoft.com", className = "fsexchange.webservice.premservice.GetPermItemInfo")
	@ResponseWrapper(localName = "getPermItemInfoResponse", targetNamespace = "http://webhallWebService.webService.tjsoft.com", className = "fsexchange.webservice.premservice.GetPermItemInfoResponse")
	public String getPermItemInfo(
			@WebParam(name = "in0", targetNamespace = "http://webhallWebService.webService.tjsoft.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://webhallWebService.webService.tjsoft.com") String in1);

}
