package fsexchange.ws.stub.businesscollect;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BusinessCollectWebServicePortType", targetNamespace = "http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com")
public interface BusinessCollectWebServicePortType {

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com")
	@RequestWrapper(localName = "saveOrUpdateBusinessCollect", targetNamespace = "http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com", className = "fsexchange.webservice.businesscollect.SaveOrUpdateBusinessCollect")
	@ResponseWrapper(localName = "saveOrUpdateBusinessCollectResponse", targetNamespace = "http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com", className = "fsexchange.webservice.businesscollect.SaveOrUpdateBusinessCollectResponse")
	public String saveOrUpdateBusinessCollect(
			@WebParam(name = "in0", targetNamespace = "http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com") String in1,
			@WebParam(name = "in2", targetNamespace = "http://busisnessCollectWebService.busisnesscollectwebservice.xservice.controlcenter.tjsoft.com") String in2);

}
