package fsexchange.ws.stub.userservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IUserServicePortType", targetNamespace = "http://service.tjsoft.com")
public interface IUserServicePortType {

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "saveUserInformation", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.SaveUserInformation")
	@ResponseWrapper(localName = "saveUserInformationResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.SaveUserInformationResponse")
	public int saveUserInformation(
			@WebParam(name = "in0", targetNamespace = "http://service.tjsoft.com") UserInformation in0,
			@WebParam(name = "in1", targetNamespace = "http://service.tjsoft.com") UserlogOn in1);

	/**
	 * 
	 * @param in0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "checkName", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.CheckName")
	@ResponseWrapper(localName = "checkNameResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.CheckNameResponse")
	public boolean checkName(
			@WebParam(name = "in0", targetNamespace = "http://service.tjsoft.com") String in0);

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "updateOrsaveUser", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.UpdateOrsaveUser")
	@ResponseWrapper(localName = "updateOrsaveUserResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.UpdateOrsaveUserResponse")
	public int updateOrsaveUser(
			@WebParam(name = "in0", targetNamespace = "http://service.tjsoft.com") ArrayOfUserlogOn in0,
			@WebParam(name = "in1", targetNamespace = "http://service.tjsoft.com") ArrayOfUserInformation in1,
			@WebParam(name = "in2", targetNamespace = "http://service.tjsoft.com") ArrayOfInc in2);

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "saveInc", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.SaveInc")
	@ResponseWrapper(localName = "saveIncResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.SaveIncResponse")
	public int saveInc(
			@WebParam(name = "in0", targetNamespace = "http://service.tjsoft.com") Inc in0,
			@WebParam(name = "in1", targetNamespace = "http://service.tjsoft.com") UserlogOn in1);

	/**
	 * 
	 * @return returns fsexchange.webservice.userservice.ArrayOfInc
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "getAllInc", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.GetAllInc")
	@ResponseWrapper(localName = "getAllIncResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.GetAllIncResponse")
	public ArrayOfInc getAllInc();

	/**
	 * 
	 * @return returns fsexchange.webservice.userservice.ArrayOfUserInformation
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "getAllUserInformation", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.GetAllUserInformation")
	@ResponseWrapper(localName = "getAllUserInformationResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.GetAllUserInformationResponse")
	public ArrayOfUserInformation getAllUserInformation();

	/**
	 * 
	 * @return returns fsexchange.webservice.userservice.ArrayOfUserlogOn
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "getAllUserlogOn", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.GetAllUserlogOn")
	@ResponseWrapper(localName = "getAllUserlogOnResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.GetAllUserlogOnResponse")
	public ArrayOfUserlogOn getAllUserlogOn();

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "encodePassword", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.EncodePassword")
	@ResponseWrapper(localName = "encodePasswordResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.EncodePasswordResponse")
	public String encodePassword(
			@WebParam(name = "in0", targetNamespace = "http://service.tjsoft.com") String in0);

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.tjsoft.com")
	@RequestWrapper(localName = "getIdByUserLogon", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.GetIdByUserLogon")
	@ResponseWrapper(localName = "getIdByUserLogonResponse", targetNamespace = "http://service.tjsoft.com", className = "fsexchange.webservice.userservice.GetIdByUserLogonResponse")
	public String getIdByUserLogon(
			@WebParam(name = "in0", targetNamespace = "http://service.tjsoft.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://service.tjsoft.com") String in1);

}
